export const trMilestones = ["ID", "Milestone Name", "Milestone Completion"]

const milestonesActivities = ["Construction of a Transmission Line", "Construction of a substation",
    "Construction of geothermal power plant.", "Geothermal Exploration and Development (105 MW Geothermal)"]
export const tdMilestones = [['1', ' Feasibility Study', 'Construction of a Transmission Line', false],
['2', ' Tender Document Preparation', 'Construction of a Transmission Line', false],
['3', ' Engineering Designs', 'Construction of a Transmission Line', false],
['4', ' Procurement of Consultant/Contractor', 'Construction of a Transmission Line', false],
['5', ' Cadastral Survey', 'Construction of a Transmission Line', false],
['6', ' Wayleave acquisition', 'Construction of a Transmission Line', false],
['7', ' Procurement of Materials', 'Construction of a Transmission Line', false],
['8', ' Tower Foundations(No)', 'Construction of a Transmission Line', false],
['9', ' Tower Erection(No)', 'Construction of a Transmission Line', false],
['10', ' Conductor/OPGW Stringing(Km)', 'Construction of a Transmission Line', false],
['11', ' Commissioning', 'Construction of a Transmission Line', false]]
const substation = [['1', ' Feasibility Study', 'Construction of a substation', false],
['2', ' Tender Document Preparation', 'Construction of a substation', false],
['3', ' Engineering Designs', 'Construction of a substation', false],
['4', ' Procurement of Consultant/Contractor', 'Construction of a substation', false],
['5', ' Cadastral Survey', 'Construction of a substation', false],
['6', ' Wayleave acquisition', 'Construction of a substation', false],
['7', ' Procurement of Materials', 'Construction of a substation', false],
['8', ' Tower Foundations(No)', 'Construction of a substation', false],
['9', ' Tower Erection(No)', 'Construction of a substation', false],
['10', ' Conductor/OPGW Stringing(Km)', 'Construction of a substation', false],
['11', ' Commissioning', 'Construction of a substation', false]]

export const trContrators = ["ID", "Contrator Name", "Active", "Date Added"]
export const tdContractors = [[0, 'Pope Inc', false, '1997-12-02'],
[1, 'Tran-Mora', false, '1987-07-11'],
[2, 'Fisher Group', false, '2002-04-14'],
[3, 'Matthews PLC', false, '2004-02-25'],
[4, 'Anderson-Smith', false, '1998-05-15'],
[5, 'Duran-Weaver', false, '1974-08-10'],
[6, 'Gordon-Richard', false, '2002-10-13'],
[7, 'Hayden Inc', false, '1985-04-01'],
[8, 'Clark PLC', false, '1980-10-02'],
[9, 'Horton LLC', false, '2005-12-11'],
[10, 'Rivera LLC', false, '1981-08-08'],
[11, 'Reese-Herrera', false, '2018-09-04'],
[12, 'Becker, Fuentes and Green', false, '1986-11-20'],
[13, 'Quinn-Vance', false, '1983-10-11'],
[14, 'Carter Ltd', false, '2008-07-19']]

export const trDonors = ["ID", "Name", "Active", "Date added"]
export const tdDonors = [[0, 'Castro, Miller and Ayers', false, '2008-08-17'],
[1, 'Miller-Proctor', false, '2011-02-25'],
[2, 'Lynn Inc', false, '2013-06-23'],
[3, 'Beltran-Hopkins', false, '1982-06-28'],
[4, 'Carter-Carter', false, '2002-10-12'],
[5, 'Brown Group', false, '2008-08-21'],
[6, 'Wilson Group', false, '2008-03-13'],
[7, 'Jones-Gonzalez', false, '2018-06-03'],
[8, 'Simon-Roberts', false, '2019-06-26'],
[9, 'Smith Inc', false, '2005-11-14'],
[10, 'Blevins-Wilcox', false, '2020-03-07'],
[11, 'Lewis, Edwards and Christensen', false, '1982-08-25'],
[12, 'Smith, Cuevas and Ryan', false, '2019-04-15'],
[13, 'Ryan, Jacobs and Brown', false, '2009-10-20'],
[14, 'Hayes Inc', false, '1991-01-22']]

export const trProjects = ["ID", "Project", "Impelenting Agency", "Project Output", "Technology", "Indicator", "County", "Consultant",
    "Contractor", "Eastings", "Nothings", "Project Cost"]

export const tdProjects = [[0,
    'Geothermal Exploration and Development (105 MW Geothermal)',
    'Bright, Frederick and Davis',
    'Central finish thousand policy.',
    'Enabling technologies',
    1,
    'Garissa',
    'Douglas Bond',
    'Jacob Herrera',
    '-43.886120',
    '-57.553383',
    'Ksh 8319'],
[1,
    'Construction of geothermal power plant.',
    'Smith LLC',
    'Base easy prove base issue general.',
    'Hydropower',
    1,
    'Wajir',
    'Lynn Price',
    'Kathy James',
    '-7.066951',
    '138.745588',
    'Ksh 9022'],
[2,
    'Construction of a substation',
    'Taylor-Dunn',
    'Discover keep item nothing debate remember whatever.',
    'Geothermal',
    1,
    'Garissa',
    'Monica Velasquez',
    'Ms. Kristen Archer',
    '-83.021608',
    '44.232281',
    'Ksh 4019'],
[3,
    'Construction of geothermal power plant.',
    'Jackson, Holt and George',
    'Send speech must.',
    'Hydropower',
    1,
    'Garissa',
    'Thomas Cruz',
    'Jason Richardson',
    '-11.867488',
    '-152.242839',
    'Ksh 6044'],
[4,
    'Construction of geothermal power plant.',
    'Smith, Salas and Russell',
    'Popular hair treat standard play prevent result.',
    'Enabling technologies',
    1,
    'Garissa',
    'Harry Williams',
    'Dr. Timothy Brooks',
    '33.234568',
    '128.763815',
    'Ksh 8292'],
[5,
    'Construction of a substation',
    'Tapia, Fitzgerald and Johnston',
    'Most visit talk between probably man.',
    'Bioenergy',
    1,
    'Wajir',
    'Alexis Wang',
    'Breanna Flores',
    '47.189456',
    '120.280935',
    'Ksh 2326'],
[6,
    'Construction of geothermal power plant.',
    'Sutton-Valdez',
    'Film in black.',
    'Solar power',
    1,
    'Kilifi',
    'Cassandra Gomez',
    'Hannah Jones',
    '40.982922',
    '-14.690804',
    'Ksh 9768'],
[7,
    'Construction of a substation',
    'Owens-Mclean',
    'Kitchen team national through recognize lead.',
    'Wind power',
    1,
    'Wajir',
    'Diane Lee',
    'David White',
    '-26.5246585',
    '-135.071050',
    'Ksh 3156'],
[8,
    'Construction of a substation',
    'Wilson-Lee',
    'Beyond let on attack.',
    'Wind power',
    1,
    'Kilifi',
    'Robert Travis',
    'Matthew Williamson',
    '-58.0505775',
    '28.929376',
    'Ksh 6031'],
[9,
    'Construction of a Transmission Line',
    'Smith-Evans',
    'Pass dog carry team artist heart this.',
    'Hydropower',
    1,
    'Garissa',
    'Marc Rowe',
    'Melanie Burke',
    '-26.5798475',
    '43.262760',
    'Ksh 2364'],
[10,
    'Construction of geothermal power plant.',
    'Weeks, Mitchell and Mendoza',
    'Work federal picture own water Mrs lose fight.',
    'Enabling technologies',
    1,
    'Lamu',
    'Frank Vasquez',
    'Denise Todd',
    '65.908838',
    '104.251514',
    'Ksh 183'],
[11,
    'Construction of a Transmission Line',
    'Hill PLC',
    'Population impact per form exactly statement cause.',
    'Wind power',
    1,
    'Garissa',
    'Michael Liu',
    'Stanley Lopez',
    '38.497901',
    '-142.562105',
    'Ksh 2916'],
[12,
    'Construction of a substation',
    'Price, Butler and Kennedy',
    'Traditional evidence follow man floor reduce.',
    'Wind power',
    1,
    'Garissa',
    'Lee Taylor',
    'Ms. Casey Martin',
    '-22.723416',
    '-0.833369',
    'Ksh 1530'],
[13,
    'Construction of geothermal power plant.',
    'Jordan, Warren and Garrett',
    'Form mean civil agree career bank of.',
    'Geothermal',
    1,
    'Mombasa',
    'Elizabeth Mcdonald',
    'Andrew Taylor',
    '32.5634025',
    '126.440584',
    'Ksh 8709'],
[14,
    'Construction of a Transmission Line',
    'Lopez, Delgado and Sosa',
    'Great road go big on easy decision.',
    'Bioenergy',
    1,
    'Tana River',
    'John Rush',
    'Martin Molina',
    '-86.160977',
    '126.591261',
    'Ksh 2868'],
[15,
    'Construction of geothermal power plant.',
    'Day Ltd',
    'Successful inside cost spend may religious.',
    'Geothermal',
    1,
    'Tana River',
    'David Macdonald',
    'Deborah Wood',
    '-64.094558',
    '178.058042',
    'Ksh 2894'],
[16,
    'Geothermal Exploration and Development (105 MW Geothermal)',
    'Vasquez-Griffin',
    'Mr into grow stage tax later sister.',
    'Wind power',
    1,
    'Mombasa',
    'Tina Fisher',
    'Daniel Sheppard',
    '-21.125734',
    '164.029685',
    'Ksh 630'],
[17,
    'Construction of geothermal power plant.',
    'Ward, Brady and Russell',
    'She piece college possible card PM.',
    'Bioenergy',
    1,
    'Wajir',
    'Adam Mills',
    'Willie Stevens',
    '-17.225834',
    '88.091435',
    'Ksh 8284'],
[18,
    'Construction of a Transmission Line',
    'Bell, Jordan and Robinson',
    'Soldier experience way determine source.',
    'Enabling technologies',
    1,
    'Mombasa',
    'Colleen Russo',
    'James Johnson',
    '-6.0915875',
    '-49.074227',
    'Ksh 2905'],
[19,
    'Geothermal Exploration and Development (105 MW Geothermal)',
    'Anderson and Sons',
    'Song month story past follow smile be.',
    'Wind power',
    1,
    'Taita Taveta',
    'Jennifer Coleman',
    'Joseph Murphy',
    '-67.408310',
    '103.437183',
    'Ksh 5499']]
