export const trMilestones = ["ID", "Milestone Name", "Milestone Completion"]

const milestonesActivities = ["Construction of a Transmission Line", "Construction of a substation",
    "Construction of geothermal power plant.", "Geothermal Exploration and Development (105 MW Geothermal)"]
export const tdMilestones = [['1', ' Feasibility Study', 'Construction of a Transmission Line', false],
['2', ' Tender Document Preparation', 'Construction of a Transmission Line', false],
['3', ' Engineering Designs', 'Construction of a Transmission Line', false],
['4', ' Procurement of Consultant/Contractor', 'Construction of a Transmission Line', false],
['5', ' Cadastral Survey', 'Construction of a Transmission Line', false],
['6', ' Wayleave acquisition', 'Construction of a Transmission Line', false],
['7', ' Procurement of Materials', 'Construction of a Transmission Line', false],
['8', ' Tower Foundations(No)', 'Construction of a Transmission Line', false],
['9', ' Tower Erection(No)', 'Construction of a Transmission Line', false],
['10', ' Conductor/OPGW Stringing(Km)', 'Construction of a Transmission Line', false],
['11', ' Commissioning', 'Construction of a Transmission Line', false]]
const substation = [['1', ' Feasibility Study', 'Construction of a substation', false],
['2', ' Tender Document Preparation', 'Construction of a substation', false],
['3', ' Engineering Designs', 'Construction of a substation', false],
['4', ' Procurement of Consultant/Contractor', 'Construction of a substation', false],
['5', ' Cadastral Survey', 'Construction of a substation', false],
['6', ' Wayleave acquisition', 'Construction of a substation', false],
['7', ' Procurement of Materials', 'Construction of a substation', false],
['8', ' Tower Foundations(No)', 'Construction of a substation', false],
['9', ' Tower Erection(No)', 'Construction of a substation', false],
['10', ' Conductor/OPGW Stringing(Km)', 'Construction of a substation', false],
['11', ' Commissioning', 'Construction of a substation', false]]

export const trContrators = ["ID", "Contrator Name", "Active", "Date Added"]
export const tdContractors = [[0, 'Pope Inc', false, '1997-12-02'],
[1, 'Tran-Mora', false, '1987-07-11'],
[2, 'Fisher Group', false, '2002-04-14'],
[3, 'Matthews PLC', false, '2004-02-25'],
[4, 'Anderson-Smith', false, '1998-05-15'],
[5, 'Duran-Weaver', false, '1974-08-10'],
[6, 'Gordon-Richard', false, '2002-10-13'],
[7, 'Hayden Inc', false, '1985-04-01'],
[8, 'Clark PLC', false, '1980-10-02'],
[9, 'Horton LLC', false, '2005-12-11'],
[10, 'Rivera LLC', false, '1981-08-08'],
[11, 'Reese-Herrera', false, '2018-09-04'],
[12, 'Becker, Fuentes and Green', false, '1986-11-20'],
[13, 'Quinn-Vance', false, '1983-10-11'],
[14, 'Carter Ltd', false, '2008-07-19']]

export const trDonors = ["ID", "Name", "Active", "Date added"]
export const tdDonors = [[0, 'Castro, Miller and Ayers', false, '2008-08-17'],
[1, 'Miller-Proctor', false, '2011-02-25'],
[2, 'Lynn Inc', false, '2013-06-23'],
[3, 'Beltran-Hopkins', false, '1982-06-28'],
[4, 'Carter-Carter', false, '2002-10-12'],
[5, 'Brown Group', false, '2008-08-21'],
[6, 'Wilson Group', false, '2008-03-13'],
[7, 'Jones-Gonzalez', false, '2018-06-03'],
[8, 'Simon-Roberts', false, '2019-06-26'],
[9, 'Smith Inc', false, '2005-11-14'],
[10, 'Blevins-Wilcox', false, '2020-03-07'],
[11, 'Lewis, Edwards and Christensen', false, '1982-08-25'],
[12, 'Smith, Cuevas and Ryan', false, '2019-04-15'],
[13, 'Ryan, Jacobs and Brown', false, '2009-10-20'],
[14, 'Hayes Inc', false, '1991-01-22']]

export const trProjects = ["ID", "Project", "Impelenting Agency", "Project Output", "Technology", "Indicator", "County", "Consultant",
    "Contractor", "Eastings", "Nothings", "Project Cost"]

export const tdProjects = [[0,
    'Geothermal Exploration and Development (105 MW Geothermal)',
    'Bright, Frederick and Davis',
    'Central finish thousand policy.',
    'Enabling technologies',
    1,
    'Garissa',
    'Douglas Bond',
    'Jacob Herrera',
    '-43.886120',
    '-57.553383',
    'Ksh 8319'],
[1,
    'Construction of geothermal power plant.',
    'Smith LLC',
    'Base easy prove base issue general.',
    'Hydropower',
    1,
    'Wajir',
    'Lynn Price',
    'Kathy James',
    '-7.066951',
    '138.745588',
    'Ksh 9022'],
[2,
    'Construction of a substation',
    'Taylor-Dunn',
    'Discover keep item nothing debate remember whatever.',
    'Geothermal',
    1,
    'Garissa',
    'Monica Velasquez',
    'Ms. Kristen Archer',
    '-83.021608',
    '44.232281',
    'Ksh 4019'],
[3,
    'Construction of geothermal power plant.',
    'Jackson, Holt and George',
    'Send speech must.',
    'Hydropower',
    1,
    'Garissa',
    'Thomas Cruz',
    'Jason Richardson',
    '-11.867488',
    '-152.242839',
    'Ksh 6044'],
[4,
    'Construction of geothermal power plant.',
    'Smith, Salas and Russell',
    'Popular hair treat standard play prevent result.',
    'Enabling technologies',
    1,
    'Garissa',
    'Harry Williams',
    'Dr. Timothy Brooks',
    '33.234568',
    '128.763815',
    'Ksh 8292'],
[5,
    'Construction of a substation',
    'Tapia, Fitzgerald and Johnston',
    'Most visit talk between probably man.',
    'Bioenergy',
    1,
    'Wajir',
    'Alexis Wang',
    'Breanna Flores',
    '47.189456',
    '120.280935',
    'Ksh 2326'],
[6,
    'Construction of geothermal power plant.',
    'Sutton-Valdez',
    'Film in black.',
    'Solar power',
    1,
    'Kilifi',
    'Cassandra Gomez',
    'Hannah Jones',
    '40.982922',
    '-14.690804',
    'Ksh 9768'],
[7,
    'Construction of a substation',
    'Owens-Mclean',
    'Kitchen team national through recognize lead.',
    'Wind power',
    1,
    'Wajir',
    'Diane Lee',
    'David White',
    '-26.5246585',
    '-135.071050',
    'Ksh 3156'],
[8,
    'Construction of a substation',
    'Wilson-Lee',
    'Beyond let on attack.',
    'Wind power',
    1,
    'Kilifi',
    'Robert Travis',
    'Matthew Williamson',
    '-58.0505775',
    '28.929376',
    'Ksh 6031'],
[9,
    'Construction of a Transmission Line',
    'Smith-Evans',
    'Pass dog carry team artist heart this.',
    'Hydropower',
    1,
    'Garissa',
    'Marc Rowe',
    'Melanie Burke',
    '-26.5798475',
    '43.262760',
    'Ksh 2364'],
[10,
    'Construction of geothermal power plant.',
    'Weeks, Mitchell and Mendoza',
    'Work federal picture own water Mrs lose fight.',
    'Enabling technologies',
    1,
    'Lamu',
    'Frank Vasquez',
    'Denise Todd',
    '65.908838',
    '104.251514',
    'Ksh 183'],
]

export const project_details = {
    "id": ["ITEM", 1],
    "project": ["Program/Project", "Olkaria"],
    "sub_project": ["Sub Project", "Olkaria 1"],
    "implementing_agency": ["Implementing Agency", "China 1 way"],
    "ouput": ["Ouput", "Complete"],
    "technology": ["Technology", "Solar power"],
    "fit_non": ["( Fit, Non Fit,n/a)", "FIT"],
    "county": ["County", "Nakuru"],
    "constituency": ["Constituency", "Naivasha"]
};
export const project_desc = {
    "project_location": ["PROJECT LOCATION", "-43.886120, -57.553383"],
    "scope_description": ["PROJECT SCOPE/ DESCRIPTION", "Only working with monitoring"],
    "benefit": ["BENEFIT", "Improve on power pofomance"],
    "finciers": ["FINANCIER(S)", "Gorverment of France", "Gorverment of China", "Treasury"],
    "consultant": ["CONSULTANT", "Dennis Kamau"],
    "contractor": ["CONTRACTOR", "Eng, Mike Sonko"]
}
export const finances = {
    "foreign": ["FOREIGN FUNDING (KES MIL)", "405"],
    "gok": ["GOK FUNDING (KES MIL)", 90],
    "direct": ["DIRECT LOAN(KES MIL)", 67],
    "other": ["OTHER CONTRIBUTION (KES MIL)", 89],
    "approved": ["APPROVED VARIATION(KES MIL)", true],
    "cumulative_expenditure": ["CUMULATIVE EXPENDITURE(KES MIL)", 456],
    "allocation": ["ALLOCATION FY 2019/2020 (KES MIL)", 678],
    "actual_expenditure": ["ACTUAL EXPENDITURE FY 2019/2020 (KES MIL)", 45],
    "balance": ["BALANCE FY 2019/2020(KES MIL)", 83]
}
export const timelines = {
    "start_date": ["START DATE", "07/05/2020"],
    "initial_completion": ["INNITIAL COMPLETION DATE", "09/4/2020"],
    "revised_completion": ["REVISED COMPLETION DATE", "09/09/2020"],
    "actual_completion": ["ACTUAL COMPLETION DATE", "04/09/2020"]
}

export const major_milestones_headers = ["ID", "Name", "Status"]
export const major_milestones = [['1', 'Land acquisition ', ""],
['2', 'Feasibility Study', 'Complete'],
['3', 'Env. Impact Assessment', 'Done and Approved'],
['4', 'Drilling and Testing of wells', 'complete.'],
['5', 'Funding Commitment', "Yes"],
['6', 'Procurement of Consultant', 'Complete'],
['7', 'Procurement of Contractor', 'Complete'],
['8', 'National Treasury Approval', 'Approved'],
['9', 'Attorney General Approval', 'Approved'],
['10', 'Lot I (Steamfield DevelopmentWorks', 'Ongoing at 93.25% Complete'],
['11', 'Lot II (Power Plant - Works', 'Ongoing at 91% Complete'],
['12', 'Lot III (HV Substation & Transmission Lines- Contractor addressing the Snag list', 'Works completed and TOC issued']]

export let challenges_headers = ["ID", "Challenge", "Mitigation", "Remarks", "Resolved"]
export const challenges = [
    [1, "Not enough money", "Got more fundings", "Let not face this again", false],
    [2, "No engineers", "Hire more", "We sgould train more engineers", true]
]